# Generated by Django 4.2.15 on 2024-08-28 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Halls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hall',
            new_name='Halls',
        ),
    ]
