# Generated by Django 4.2.15 on 2024-08-28 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Halls', '0002_rename_hall_halls'),
    ]

    operations = [
        migrations.AddField(
            model_name='halls',
            name='body',
            field=models.TextField(default='Default Text'),
        ),
        migrations.CreateModel(
            name='Shar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('halls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shar', to='Halls.halls')),
            ],
            options={
                'ordering': ['created'],
                'indexes': [models.Index(fields=['created'], name='Halls_shar_created_510f19_idx')],
            },
        ),
    ]
