# Generated by Django 4.2.15 on 2024-08-29 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Halls', '0003_halls_body_shar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halls',
            name='capacity',
            field=models.IntegerField(max_length=250),
        ),
        migrations.AlterField(
            model_name='halls',
            name='price',
            field=models.IntegerField(max_length=10),
        ),
    ]
