# Generated by Django 4.2.15 on 2024-08-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Halls', '0004_alter_halls_capacity_alter_halls_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='halls',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
