# Generated by Django 4.2.15 on 2024-08-29 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Halls', '0005_halls_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=180)),
                ('halls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ؤlient', to='Halls.halls')),
            ],
        ),
    ]
