# Generated by Django 4.2.15 on 2024-08-29 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Halls', '0006_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='halls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to='Halls.halls'),
        ),
    ]
