# Generated by Django 4.2.15 on 2024-08-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Halls', '0007_alter_client_halls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='halls',
        ),
        migrations.AlterField(
            model_name='halls',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='halls',
            name='price',
            field=models.IntegerField(),
        ),
    ]
