# Generated by Django 4.2.15 on 2024-08-29 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Halls', '0008_remove_client_halls_alter_halls_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='halls',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='halls', to='Halls.client'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
