# Generated by Django 4.2.15 on 2024-08-29 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Halls', '0009_halls_client_alter_client_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='halls',
            name='client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
