# Generated by Django 4.2.15 on 2024-08-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Halls', '0011_client_halls_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
