# Generated by Django 4.2.15 on 2024-09-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Halls', '0012_alter_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='halls',
            name='slug',
            field=models.SlugField(default=1, max_length=250, unique_for_date='publish'),
            preserve_default=False,
        ),
    ]
