# Generated by Django 4.2.15 on 2024-09-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Halls', '0013_halls_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halls',
            name='body',
            field=models.TextField(blank=True, default='Default Text'),
        ),
        migrations.AlterField(
            model_name='halls',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
