# Generated by Django 4.2.15 on 2024-09-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Halls', '0014_alter_halls_body_alter_halls_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halls',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y'),
        ),
    ]
