# Generated by Django 4.2.15 on 2024-09-06 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Halls', '0015_alter_halls_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images_client/%Y'),
        ),
    ]
