# Generated by Django 4.2.15 on 2024-09-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Halls', '0018_alter_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='photo',
        ),
    ]
