# Generated by Django 4.2.15 on 2024-09-18 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Halls', '0019_remove_client_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='last_login',
        ),
    ]
