# Generated by Django 4.2.15 on 2024-10-01 14:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Halls', '0021_alter_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='halls',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
